apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}--secret
  env: dev
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}

